langage = {
	1:{path:"/wap/app_img/h/ch/",
		sl1:"运动侦测报警",
		hl1:"打开运动侦测报警后，当采集端画面发生变化你也可以收到推送报警和邮件报警，并且在您的采集端会同时触发录制报警。",
		sl2:"定时录制",
		hl2:"打开定时录制后，采集端会在设定时间内开启录制，并将录制文件存储在采集端。",
		sl3:"双向语音",
		hl3:"“按住对讲”可以实现与对端实时通话，实现双向沟通。",
		sl4:"前后摄像头切换",
		hl4:"当连接手机采集端时，可以通过“切换”按钮在手机前后摄像头间转换。",
		sl5:"本地录制",
		hl5:"在观看实时视频的过程中，可以通过点击“录制”按钮将视频录制到本地相册中。",
		sl6:"一键解除/开启报警",
		hl6:"运动侦测报警配置好后，可以通过列表展开菜单内的报警快捷开关来快速开启或关闭报警功能。",
		sl7:"视频截图",
		hl7:"在观看实时视频的过程中，可以通过点击“截屏”按钮将当前视频页面截取到本地相册中",
		sl8:"开启闪光灯",
		hl8:"当连接手机采集端时，可以通过“闪光灯”按钮远程开启手机上的闪光灯，方便夜间查看。"
	},
	2:{path:"/wap/app_img/h/en/",
		sl1:"Motion Detection",
		hl1:"When motion detection is triggered you can receive email alerts and push notifications. Your camera will also automatically begin recording. Motion detection settings can be customized in the Motion Detection menu.",
		sl2:"Scheduled Recordings",
		hl2:"Opening the Scheduled Recordings menu allows you to customize when the AtHome Video Streamer begins recording. All scheduled recordings are saved in the AtHome Video Streamer device.",
		sl3:"Two-Way Communication",
		hl3:"Hold down the ‘Hold to Talk’ button to communicate with the AtHome Video Streamer. Enhanced audio communication allows you to speak and listen simultaneously.",
		sl4:"Switch between front and back-facing cameras",
		hl4:"If you are using a smartphone as the AtHome Video Streamer, you can switch between the front and back-facing cameras remotely using the “Switch” button in the AtHome Camera app.",
		sl5:"Manual Recording",
		hl5:"At anytime while watching the surveillance feed, you can manually begin recording by tapping the ‘Record’ button. Videos recorded manually are saved in your phone or tablet’s media folder (the device with AtHome Camera installed).",
		sl6:"Toggle On/Off Motion Detection",
		hl6:"Once time interval and sensitivity settings have been set, expanding the quick menu allows you to easily toggle motion detection alarms on and off.",
		sl7:"Screen Capture",
		hl7:"While watching the surveillance feed, you can capture a screenshot of the video at its current time. The screenshot is then saved to your phone’s photo album.",
		sl8:"Flash",
		hl8:"If you are using a smartphone as the AtHome Video Streamer, you can remotely enable flash for better nighttime viewing. Enable flash by tapping the ‘Flash’ button in the AtHome Camera app."
	},
	3:{path:"/wap/app_img/h/ch/",
		sl1:"運動偵測報警",
		hl1:"打開運動偵測報警後，當采集端畫面發生變化妳也可以收到推送報警和郵件報警，並且在您的采集端會同時觸發錄制報警。",
		sl2:"定時錄制",
		hl2:"打開定時錄制後，采集端會在設定時間內開啓錄制，並將錄制文件存儲在采集端。",
		sl3:"雙向語音",
		hl3:"“按住對講”可以實現與對端實時通話，實現雙向溝通。",
		sl4:"前後攝像頭切換",
		hl4:"當連接手機采集端時，可以通過“切換”按鈕在手機前後攝像頭間轉換。",
		sl5:"本地錄制",
		hl5:"在觀看實時視頻的過程中，可以通過點擊“錄制”按鈕將視頻錄制到本地相冊中。",
		sl6:"壹鍵解除/開啓報警",
		hl6:"運動偵測報警配置好後，可以通過列表展開菜單內的報警快捷開關來快速開啓或關閉報警功能。",
		sl7:"視頻截圖",
		hl7:"在觀看實時視頻的過程中，可以通過點擊“截屏”按鈕將當前視頻頁面截取到本地相冊中",
		sl8:"開啓閃光燈",
		hl8:"當連接手機采集端時，可以通過“閃光燈”按鈕遠程開啓手機上的閃光燈，方便夜間查看。"
	}
}